### ISSUE TITLE
Save Downloaded Files to New Folder

### ISSUE THREAD

**Issue by FreddieV4** [FreddieV4/VScraper#10]
Makes it easier for people to drag all of the downloaded files into another directory.

**Comment by Altoidnerd** [comment]
can use

import os
out_dir = '/path/to/dir'
os.system("mkdir {}".format(out_dir)

**Comment by FreddieV4** [comment]
Yeah I was looking at the `os` library and saw this. Thanks for the code snippet.

**Comment by Altoidnerd** [comment]
Would be nice to have a similar thing - allow an out_dir specified as an argument, and if absent prompt user.  

I should overhaul the way I implemented the args, so that we can add arbitrary options in a clean extensible way.  The lib is called argparse...  Ill start on that next.

**Comment by FreddieV4** [comment]
### Done
Created new parameter `out_dir` which uses `file_type` as the name of the folder that's created. Creates new folder with name `file_type` and adds files to that folder.
